spring:
  application:
    name: ^project.name^
    description: ^project.description^ 
    version: ^project.version^
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:employeedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari: 
      maximum-pool-size: 20
      minimum-idle: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: spring-zipkin-metrics
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
  tracing:
    sampling:
      probability: 1.0
springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    com.mc.employee: DEBUG
    org.springframework.cache: DEBUG
    com.zaxxer.hikari: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M:%line traceId=%X{traceId:-} - %msg%n"
    
server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: dev
  zipkin:
    base-url: http://localhost:9411
    service:
      name: spring-zipkin-metrics

---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    enabled: true
    key-store: classpath:certs/mc-employee-api.p12
    key-store-password: changeit
    key-store-type: pkcs12
    key-alias: mc-employee-api
    key-password: changeit
  port: 8443

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    com.mc.employee: INFO
    org.springframework.cache: INFO
    com.zaxxer.hikari: INFO
