spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:employeedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  zipkin:
    enabled: false
    base-url: http://localhost:9411/
    service:
      name: spring-zipkin-metrics
      
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.mc.employee: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M:%line - %msg%n"
    
---
spring:
  config:
    activate:
      on-profile: dev
  zipkin:
    enabled: false
    base-url: http://localhost:9411
    service:
      name: spring-zipkin-metrics

---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    enabled: true
    key-store: classpath:certs/mc-employee-api.p12
    key-store-password: changeit
    key-store-type: pkcs12
    key-alias: mc-employee-api
    key-password: changeit
  port: 8443
